entrada = input("Por favor ingrese palabras separadas por espacios, para formar una lista: ")
lista = entrada.split()
lista1 = entrada.split()
lista1.reverse()
print(f"La lista original es {lista} y la invertida es {lista1}")